---
title: "Course support"
---

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help.

## Lectures and labs

If you have a question during lecture or lab, feel free to ask it!
There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

The teaching team is here to help you be successful in the course.
You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments.
A lot of questions are most effectively answered in-person, so office hours are a valuable resource.
I encourage each and every one of you to take advantage of this resource!
Make a pledge to stop by office hours at least once during the first three weeks of class.
If you truly have no questions to ask, just stop by and say hi and introduce yourself.
You can find a list of everyone's office hours [here](/course-team.html).

## Discussion forum

Have a question that can't wait for office hours?
Prefer to write out your question in detail rather than asking in person?
The online discussion forum is the best venue for these!
We will use [Slack](https:) as the online discussion forum.
There is a chance another student has already asked a similar question, so please check the other posts on Ed Discussion before adding a new question.
If you know the answer to a question that is posted, I encourage you to respond!

## Email

Please refrain from emailing any course content questions (those should go [Slack](https:), and only use email for questions about personal matters that may not be appropriate for the public course forum (e.g., illness, accommodations, etc.).

For such matters, you may email Dr. Woods at [woodsj\@pdx.edu](mailto:woodsj@pdx.edu).

If there is a question that's not appropriate for the public forum, you are welcome to email me directly.
**If you email me, please include "Public Utility" in the subject line.** Barring extenuating circumstances, I will respond to  emails within 48 hours Monday - Friday.
Response time may be slower for emails sent Friday evening - Sunday.

## Academic support

Note that we will be making minimal use of Canvas in this course (primarily as a way of submitting assignments and grade book).

